Pin node-fetch version as workaround to thrown syntax error
In v2.2.0, node-fetch/lib/index.mjs throws an error:
    SyntaxError: Missing export 'PassThrough' in ES module: stream
v2.1.2 is fine.