Pin Cypress to v3.1.0 as v3.1.1 causes strange test failures
On some tests (but not others), cypress@3.1.1 fails with errors like:

CypressError: cy.visit() failed trying to load:

http://report.thewhistle.local:3000/grn-test/rape-is-a-crime

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > TypeError: Cannot set property 'url' of undefined

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer